// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: giga_synth_controls

#include "../ui.h"

void ui_fm_screen_screen_init(void)
{
    ui_fm_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_fm_screen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_flex_flow(ui_fm_screen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_fm_screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_fm_screen_tab = lv_tabview_create(ui_fm_screen, LV_DIR_BOTTOM, 100);
    lv_obj_set_width(ui_fm_screen_tab, 800);
    lv_obj_set_height(ui_fm_screen_tab, 480);
    lv_obj_set_x(ui_fm_screen_tab, 0);
    lv_obj_set_y(ui_fm_screen_tab, -1);
    lv_obj_set_align(ui_fm_screen_tab, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fm_screen_tab, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_fm_screen_tab), &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fm_screen_engine_page = lv_tabview_add_tab(ui_fm_screen_tab, "ENGINE");
    lv_obj_set_flex_flow(ui_fm_screen_engine_page, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_fm_screen_engine_page, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fm_screen_engine_page,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_fm_screen_fm_engine_button = lv_btn_create(ui_fm_screen_engine_page);
    lv_obj_set_width(ui_fm_screen_fm_engine_button, 350);
    lv_obj_set_height(ui_fm_screen_fm_engine_button, 150);
    lv_obj_set_align(ui_fm_screen_fm_engine_button, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fm_screen_fm_engine_button,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_fm_screen_fm_engine_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fm_screen_fm_engine_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fm_screen_fm_engine_button_label = lv_label_create(ui_fm_screen_fm_engine_button);
    lv_obj_set_width(ui_fm_screen_fm_engine_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fm_screen_fm_engine_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fm_screen_fm_engine_button_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_fm_screen_fm_engine_button_label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_fm_screen_fm_engine_button_label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_fm_screen_fm_engine_button_label, "FM");
    lv_obj_clear_flag(ui_fm_screen_fm_engine_button_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_fm_screen_fm_engine_button_label, &lv_font_montserrat_32,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fm_screen_sampler_engine_button = lv_btn_create(ui_fm_screen_engine_page);
    lv_obj_set_width(ui_fm_screen_sampler_engine_button, 350);
    lv_obj_set_height(ui_fm_screen_sampler_engine_button, 150);
    lv_obj_set_align(ui_fm_screen_sampler_engine_button, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fm_screen_sampler_engine_button,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_fm_screen_sampler_engine_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fm_screen_sampler_engine_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fm_screen_sampler_engine_button_label = lv_label_create(ui_fm_screen_sampler_engine_button);
    lv_obj_set_width(ui_fm_screen_sampler_engine_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fm_screen_sampler_engine_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fm_screen_sampler_engine_button_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_fm_screen_sampler_engine_button_label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_fm_screen_sampler_engine_button_label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_fm_screen_sampler_engine_button_label, "SAMPLER");
    lv_obj_clear_flag(ui_fm_screen_sampler_engine_button_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_fm_screen_sampler_engine_button_label, &lv_font_montserrat_32,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fm_screen_additive_engine_button = lv_btn_create(ui_fm_screen_engine_page);
    lv_obj_set_width(ui_fm_screen_additive_engine_button, 350);
    lv_obj_set_height(ui_fm_screen_additive_engine_button, 150);
    lv_obj_set_align(ui_fm_screen_additive_engine_button, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fm_screen_additive_engine_button,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_fm_screen_additive_engine_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fm_screen_additive_engine_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fm_screen_additive_engine_button_label = lv_label_create(ui_fm_screen_additive_engine_button);
    lv_obj_set_width(ui_fm_screen_additive_engine_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fm_screen_additive_engine_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fm_screen_additive_engine_button_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_fm_screen_additive_engine_button_label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_fm_screen_additive_engine_button_label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_fm_screen_additive_engine_button_label, "ADDITIVE");
    lv_obj_clear_flag(ui_fm_screen_additive_engine_button_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_fm_screen_additive_engine_button_label, &lv_font_montserrat_32,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fm_screen_subtractive_engine_button = lv_btn_create(ui_fm_screen_engine_page);
    lv_obj_set_width(ui_fm_screen_subtractive_engine_button, 350);
    lv_obj_set_height(ui_fm_screen_subtractive_engine_button, 150);
    lv_obj_set_align(ui_fm_screen_subtractive_engine_button, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fm_screen_subtractive_engine_button,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_fm_screen_subtractive_engine_button, lv_color_hex(0x292831),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fm_screen_subtractive_engine_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fm_screen_subtractive_engine_button_label = lv_label_create(ui_fm_screen_subtractive_engine_button);
    lv_obj_set_width(ui_fm_screen_subtractive_engine_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fm_screen_subtractive_engine_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fm_screen_subtractive_engine_button_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_fm_screen_subtractive_engine_button_label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_fm_screen_subtractive_engine_button_label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_fm_screen_subtractive_engine_button_label, "SUBTRACTIVE");
    lv_obj_clear_flag(ui_fm_screen_subtractive_engine_button_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_fm_screen_subtractive_engine_button_label, &lv_font_montserrat_32,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_algorithm_page = lv_tabview_add_tab(ui_fm_screen_tab, "ALGORITHM");
    lv_obj_set_flex_flow(ui_algorithm_page, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_algorithm_page, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_algorithm_page,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_algorithm_roller = lv_roller_create(ui_algorithm_page);
    lv_roller_set_options(ui_algorithm_roller,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_algorithm_roller, 70);
    lv_obj_set_height(ui_algorithm_roller, 320);
    lv_obj_set_x(ui_algorithm_roller, -13);
    lv_obj_set_y(ui_algorithm_roller, -362);
    lv_obj_set_align(ui_algorithm_roller, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_algorithm_roller,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_algorithm_container = lv_obj_create(ui_algorithm_page);
    lv_obj_remove_style_all(ui_algorithm_container);
    lv_obj_set_width(ui_algorithm_container, 650);
    lv_obj_set_height(ui_algorithm_container, 320);
    lv_obj_set_x(ui_algorithm_container, -296);
    lv_obj_set_y(ui_algorithm_container, 142);
    lv_obj_set_align(ui_algorithm_container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_algorithm_container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_algorithm_bar_11 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_11, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_11, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_11, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_11, 6);
    lv_obj_set_height(ui_algorithm_bar_11, 20);
    lv_obj_set_x(ui_algorithm_bar_11, 322);
    lv_obj_set_y(ui_algorithm_bar_11, 5);
    lv_obj_set_align(ui_algorithm_bar_11, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_11,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_11, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_11, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_algorithm_bar_10 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_10, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_10, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_10, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_10, 6);
    lv_obj_set_height(ui_algorithm_bar_10, 20);
    lv_obj_set_x(ui_algorithm_bar_10, 322);
    lv_obj_set_y(ui_algorithm_bar_10, 5);
    lv_obj_set_align(ui_algorithm_bar_10, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_10,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_10, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_10, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_algorithm_bar_9 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_9, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_9, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_9, 6);
    lv_obj_set_height(ui_algorithm_bar_9, 20);
    lv_obj_set_x(ui_algorithm_bar_9, 322);
    lv_obj_set_y(ui_algorithm_bar_9, 5);
    lv_obj_set_align(ui_algorithm_bar_9, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_9,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_9, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_algorithm_bar_8 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_8, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_8, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_8, 6);
    lv_obj_set_height(ui_algorithm_bar_8, 20);
    lv_obj_set_x(ui_algorithm_bar_8, 322);
    lv_obj_set_y(ui_algorithm_bar_8, 5);
    lv_obj_set_align(ui_algorithm_bar_8, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_8,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_8, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_algorithm_bar_7 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_7, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_7, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_7, 6);
    lv_obj_set_height(ui_algorithm_bar_7, 20);
    lv_obj_set_x(ui_algorithm_bar_7, 322);
    lv_obj_set_y(ui_algorithm_bar_7, 5);
    lv_obj_set_align(ui_algorithm_bar_7, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_7,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_7, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_algorithm_bar_6 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_6, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_6, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_6, 111);
    lv_obj_set_height(ui_algorithm_bar_6, 6);
    lv_obj_set_x(ui_algorithm_bar_6, 269);
    lv_obj_set_y(ui_algorithm_bar_6, -11);
    lv_obj_set_align(ui_algorithm_bar_6, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_6,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_6, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_algorithm_bar_5 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_5, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_5, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_5, 6);
    lv_obj_set_height(ui_algorithm_bar_5, 92);
    lv_obj_set_x(ui_algorithm_bar_5, 269);
    lv_obj_set_y(ui_algorithm_bar_5, -11);
    lv_obj_set_align(ui_algorithm_bar_5, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_5,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_5, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_algorithm_bar_4 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_4, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_4, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_4, 6);
    lv_obj_set_height(ui_algorithm_bar_4, 298);
    lv_obj_set_x(ui_algorithm_bar_4, 374);
    lv_obj_set_y(ui_algorithm_bar_4, -11);
    lv_obj_set_align(ui_algorithm_bar_4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_4,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_algorithm_bar_3 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_3, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_3, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_3, 18);
    lv_obj_set_height(ui_algorithm_bar_3, 6);
    lv_obj_set_x(ui_algorithm_bar_3, 415);
    lv_obj_set_y(ui_algorithm_bar_3, -268);
    lv_obj_set_align(ui_algorithm_bar_3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_3,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_algorithm_bar_2 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_2, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_2, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_2, 6);
    lv_obj_set_height(ui_algorithm_bar_2, 41);
    lv_obj_set_x(ui_algorithm_bar_2, 427);
    lv_obj_set_y(ui_algorithm_bar_2, -268);
    lv_obj_set_align(ui_algorithm_bar_2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_2,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_algorithm_bar_1 = lv_bar_create(ui_algorithm_container);
    lv_bar_set_range(ui_algorithm_bar_1, 0, 1);
    lv_bar_set_value(ui_algorithm_bar_1, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_algorithm_bar_1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_algorithm_bar_1, 58);
    lv_obj_set_height(ui_algorithm_bar_1, 6);
    lv_obj_set_x(ui_algorithm_bar_1, 374);
    lv_obj_set_y(ui_algorithm_bar_1, -303);
    lv_obj_set_align(ui_algorithm_bar_1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_algorithm_bar_1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_algorithm_bar_1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_algorithm_bar_1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_operator_1_button = lv_btn_create(ui_algorithm_container);
    lv_obj_set_width(ui_operator_1_button, 85);
    lv_obj_set_height(ui_operator_1_button, 50);
    lv_obj_set_x(ui_operator_1_button, 230);
    lv_obj_set_y(ui_operator_1_button, -24);
    lv_obj_set_align(ui_operator_1_button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_operator_1_button,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_operator_1_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_operator_1_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_operator_1_button, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_operator_1_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_operator_1_button, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_1_button_label = lv_label_create(ui_operator_1_button);
    lv_obj_set_width(ui_operator_1_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_1_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_1_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_1_button_label, "1");
    lv_obj_set_style_text_font(ui_operator_1_button_label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_2_button = lv_btn_create(ui_algorithm_container);
    lv_obj_set_width(ui_operator_2_button, 85);
    lv_obj_set_height(ui_operator_2_button, 50);
    lv_obj_set_x(ui_operator_2_button, 230);
    lv_obj_set_y(ui_operator_2_button, -98);
    lv_obj_set_align(ui_operator_2_button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_operator_2_button,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_operator_2_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_operator_2_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_operator_2_button, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_operator_2_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_operator_2_button, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_2_button_label = lv_label_create(ui_operator_2_button);
    lv_obj_set_width(ui_operator_2_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_2_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_2_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_2_button_label, "2");
    lv_obj_set_style_text_font(ui_operator_2_button_label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_3_button = lv_btn_create(ui_algorithm_container);
    lv_obj_set_width(ui_operator_3_button, 85);
    lv_obj_set_height(ui_operator_3_button, 50);
    lv_obj_set_x(ui_operator_3_button, 335);
    lv_obj_set_y(ui_operator_3_button, -24);
    lv_obj_set_align(ui_operator_3_button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_operator_3_button,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_operator_3_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_operator_3_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_operator_3_button, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_operator_3_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_operator_3_button, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_3_button_label = lv_label_create(ui_operator_3_button);
    lv_obj_set_width(ui_operator_3_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_3_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_3_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_3_button_label, "3");
    lv_obj_set_style_text_font(ui_operator_3_button_label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_4_button = lv_btn_create(ui_algorithm_container);
    lv_obj_set_width(ui_operator_4_button, 85);
    lv_obj_set_height(ui_operator_4_button, 50);
    lv_obj_set_x(ui_operator_4_button, 335);
    lv_obj_set_y(ui_operator_4_button, -98);
    lv_obj_set_align(ui_operator_4_button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_operator_4_button,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_operator_4_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_operator_4_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_operator_4_button, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_operator_4_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_operator_4_button, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_4_button_label = lv_label_create(ui_operator_4_button);
    lv_obj_set_width(ui_operator_4_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_4_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_4_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_4_button_label, "4");
    lv_obj_set_style_text_font(ui_operator_4_button_label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_5_button = lv_btn_create(ui_algorithm_container);
    lv_obj_set_width(ui_operator_5_button, 85);
    lv_obj_set_height(ui_operator_5_button, 50);
    lv_obj_set_x(ui_operator_5_button, 335);
    lv_obj_set_y(ui_operator_5_button, -172);
    lv_obj_set_align(ui_operator_5_button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_operator_5_button,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_operator_5_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_operator_5_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_operator_5_button, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_operator_5_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_operator_5_button, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_5_button_label = lv_label_create(ui_operator_5_button);
    lv_obj_set_width(ui_operator_5_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_5_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_5_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_5_button_label, "5");
    lv_obj_set_style_text_font(ui_operator_5_button_label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_6_button = lv_btn_create(ui_algorithm_container);
    lv_obj_set_width(ui_operator_6_button, 85);
    lv_obj_set_height(ui_operator_6_button, 50);
    lv_obj_set_x(ui_operator_6_button, 335);
    lv_obj_set_y(ui_operator_6_button, -246);
    lv_obj_set_align(ui_operator_6_button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_operator_6_button,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_operator_6_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_operator_6_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_operator_6_button, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_operator_6_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_operator_6_button, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_6_button_label = lv_label_create(ui_operator_6_button);
    lv_obj_set_width(ui_operator_6_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_6_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_6_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_6_button_label, "6");
    lv_obj_set_style_text_font(ui_operator_6_button_label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waveform_page = lv_tabview_add_tab(ui_fm_screen_tab, "WAVEFORM");
    lv_obj_set_flex_flow(ui_waveform_page, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_waveform_page, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_waveform_page, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_sine_wave_button = lv_btn_create(ui_waveform_page);
    lv_obj_set_width(ui_sine_wave_button, 350);
    lv_obj_set_height(ui_sine_wave_button, 150);
    lv_obj_set_x(ui_sine_wave_button, 15);
    lv_obj_set_y(ui_sine_wave_button, 0);
    lv_obj_clear_flag(ui_sine_wave_button,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_sine_wave_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sine_wave_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sine_wave_button_label = lv_label_create(ui_sine_wave_button);
    lv_obj_set_width(ui_sine_wave_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sine_wave_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sine_wave_button_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_sine_wave_button_label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_sine_wave_button_label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_sine_wave_button_label, "SINE WAVE");
    lv_obj_clear_flag(ui_sine_wave_button_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_sine_wave_button_label, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_square_wave_button = lv_btn_create(ui_waveform_page);
    lv_obj_set_width(ui_square_wave_button, 350);
    lv_obj_set_height(ui_square_wave_button, 150);
    lv_obj_set_x(ui_square_wave_button, -15);
    lv_obj_set_y(ui_square_wave_button, 0);
    lv_obj_set_align(ui_square_wave_button, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_square_wave_button,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_square_wave_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_square_wave_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_square_wave_button_label = lv_label_create(ui_square_wave_button);
    lv_obj_set_width(ui_square_wave_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_square_wave_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_square_wave_button_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_square_wave_button_label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_square_wave_button_label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_square_wave_button_label, "SQUARE WAVE");
    lv_obj_clear_flag(ui_square_wave_button_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_square_wave_button_label, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_triangle_wave_button = lv_btn_create(ui_waveform_page);
    lv_obj_set_width(ui_triangle_wave_button, 350);
    lv_obj_set_height(ui_triangle_wave_button, 150);
    lv_obj_set_x(ui_triangle_wave_button, 15);
    lv_obj_set_y(ui_triangle_wave_button, 180);
    lv_obj_clear_flag(ui_triangle_wave_button,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_triangle_wave_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_triangle_wave_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_triangle_wave_button_label = lv_label_create(ui_triangle_wave_button);
    lv_obj_set_width(ui_triangle_wave_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_triangle_wave_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_triangle_wave_button_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_triangle_wave_button_label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_triangle_wave_button_label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_triangle_wave_button_label, "TRIANGLE WAVE");
    lv_obj_clear_flag(ui_triangle_wave_button_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_triangle_wave_button_label, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sawtooth_wave_button = lv_btn_create(ui_waveform_page);
    lv_obj_set_width(ui_sawtooth_wave_button, 350);
    lv_obj_set_height(ui_sawtooth_wave_button, 150);
    lv_obj_set_x(ui_sawtooth_wave_button, -15);
    lv_obj_set_y(ui_sawtooth_wave_button, 180);
    lv_obj_set_align(ui_sawtooth_wave_button, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_sawtooth_wave_button,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_sawtooth_wave_button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sawtooth_wave_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sawtooth_wave_button_label = lv_label_create(ui_sawtooth_wave_button);
    lv_obj_set_width(ui_sawtooth_wave_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sawtooth_wave_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sawtooth_wave_button_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_sawtooth_wave_button_label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_sawtooth_wave_button_label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_sawtooth_wave_button_label, "SAWTOOTH WAVE");
    lv_obj_clear_flag(ui_sawtooth_wave_button_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_sawtooth_wave_button_label, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adsr_page = lv_tabview_add_tab(ui_fm_screen_tab, "ADSR");
    lv_obj_set_flex_flow(ui_adsr_page, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_adsr_page, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_adsr_page, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_adsr_labels_container = lv_obj_create(ui_adsr_page);
    lv_obj_remove_style_all(ui_adsr_labels_container);
    lv_obj_set_width(ui_adsr_labels_container, 800);
    lv_obj_set_height(ui_adsr_labels_container, 30);
    lv_obj_set_align(ui_adsr_labels_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_adsr_labels_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_adsr_labels_container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_adsr_labels_container,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_attack_label = lv_label_create(ui_adsr_labels_container);
    lv_obj_set_width(ui_attack_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_attack_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_attack_label, -285);
    lv_obj_set_y(ui_attack_label, -100);
    lv_obj_set_align(ui_attack_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_attack_label, " ATTACK");
    lv_obj_clear_flag(ui_attack_label, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_attack_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_decay_label = lv_label_create(ui_adsr_labels_container);
    lv_obj_set_width(ui_decay_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_decay_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_decay_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_decay_label, "  DECAY");
    lv_obj_clear_flag(ui_decay_label, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_decay_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sustain_label = lv_label_create(ui_adsr_labels_container);
    lv_obj_set_width(ui_sustain_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sustain_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sustain_label, 95);
    lv_obj_set_y(ui_sustain_label, -100);
    lv_obj_set_align(ui_sustain_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sustain_label, "  SUSTAIN");
    lv_obj_clear_flag(ui_sustain_label, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_sustain_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_release_label = lv_label_create(ui_adsr_labels_container);
    lv_obj_set_width(ui_release_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_release_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_release_label, 285);
    lv_obj_set_y(ui_release_label, -100);
    lv_obj_set_align(ui_release_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_release_label, "RELEASE");
    lv_obj_clear_flag(ui_release_label, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_release_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adsr_arcs_container = lv_obj_create(ui_adsr_page);
    lv_obj_remove_style_all(ui_adsr_arcs_container);
    lv_obj_set_width(ui_adsr_arcs_container, 800);
    lv_obj_set_height(ui_adsr_arcs_container, 160);
    lv_obj_set_align(ui_adsr_arcs_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_adsr_arcs_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_adsr_arcs_container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_adsr_arcs_container,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_attack_arc = lv_arc_create(ui_adsr_arcs_container);
    lv_obj_set_width(ui_attack_arc, 150);
    lv_obj_set_height(ui_attack_arc, 150);
    lv_obj_set_x(ui_attack_arc, -301);
    lv_obj_set_y(ui_attack_arc, 55);
    lv_obj_set_align(ui_attack_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_attack_arc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_attack_arc, 1, 100);
    lv_arc_set_value(ui_attack_arc, 80);


    ui_decay_arc = lv_arc_create(ui_adsr_arcs_container);
    lv_obj_set_width(ui_decay_arc, 150);
    lv_obj_set_height(ui_decay_arc, 150);
    lv_obj_set_x(ui_decay_arc, -95);
    lv_obj_set_y(ui_decay_arc, 50);
    lv_obj_set_align(ui_decay_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_decay_arc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_decay_arc, 1, 100);
    lv_arc_set_value(ui_decay_arc, 80);


    ui_sustain_arc = lv_arc_create(ui_adsr_arcs_container);
    lv_obj_set_width(ui_sustain_arc, 150);
    lv_obj_set_height(ui_sustain_arc, 150);
    lv_obj_set_x(ui_sustain_arc, 95);
    lv_obj_set_y(ui_sustain_arc, 50);
    lv_obj_set_align(ui_sustain_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sustain_arc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_sustain_arc, 80);


    ui_release_arc = lv_arc_create(ui_adsr_arcs_container);
    lv_obj_set_width(ui_release_arc, 150);
    lv_obj_set_height(ui_release_arc, 150);
    lv_obj_set_x(ui_release_arc, 285);
    lv_obj_set_y(ui_release_arc, 50);
    lv_obj_set_align(ui_release_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_release_arc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_release_arc, 1, 100);
    lv_arc_set_value(ui_release_arc, 80);


    ui_operators_page = lv_tabview_add_tab(ui_fm_screen_tab, "OPERATORS");
    lv_obj_set_flex_flow(ui_operators_page, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_operators_page, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operators_page,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_operators_ratios_label = lv_label_create(ui_operators_page);
    lv_obj_set_width(ui_operators_ratios_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operators_ratios_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operators_ratios_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_operators_ratios_label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_operators_ratios_label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_operators_ratios_label, "____________________ RATIOS ____________________");
    lv_obj_clear_flag(ui_operators_ratios_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_operators_ratios_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operators_ratios_arcs_container = lv_obj_create(ui_operators_page);
    lv_obj_remove_style_all(ui_operators_ratios_arcs_container);
    lv_obj_set_width(ui_operators_ratios_arcs_container, 800);
    lv_obj_set_height(ui_operators_ratios_arcs_container, 110);
    lv_obj_set_align(ui_operators_ratios_arcs_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_operators_ratios_arcs_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_operators_ratios_arcs_container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operators_ratios_arcs_container,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_operator_1_ratio = lv_arc_create(ui_operators_ratios_arcs_container);
    lv_obj_set_width(ui_operator_1_ratio, 100);
    lv_obj_set_height(ui_operator_1_ratio, 100);
    lv_obj_set_align(ui_operator_1_ratio, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_1_ratio,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_operator_1_ratio, 1, 64);
    lv_arc_set_value(ui_operator_1_ratio, 2);


    ui_operator_2_ratio = lv_arc_create(ui_operators_ratios_arcs_container);
    lv_obj_set_width(ui_operator_2_ratio, 100);
    lv_obj_set_height(ui_operator_2_ratio, 100);
    lv_obj_set_align(ui_operator_2_ratio, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_2_ratio,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_operator_2_ratio, 1, 64);
    lv_arc_set_value(ui_operator_2_ratio, 2);


    ui_operator_3_ratio = lv_arc_create(ui_operators_ratios_arcs_container);
    lv_obj_set_width(ui_operator_3_ratio, 100);
    lv_obj_set_height(ui_operator_3_ratio, 100);
    lv_obj_set_align(ui_operator_3_ratio, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_3_ratio,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_operator_3_ratio, 1, 64);
    lv_arc_set_value(ui_operator_3_ratio, 2);


    ui_operator_4_ratio = lv_arc_create(ui_operators_ratios_arcs_container);
    lv_obj_set_width(ui_operator_4_ratio, 100);
    lv_obj_set_height(ui_operator_4_ratio, 100);
    lv_obj_set_align(ui_operator_4_ratio, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_4_ratio,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_operator_4_ratio, 1, 64);
    lv_arc_set_value(ui_operator_4_ratio, 2);


    ui_operator_5_ratio = lv_arc_create(ui_operators_ratios_arcs_container);
    lv_obj_set_width(ui_operator_5_ratio, 100);
    lv_obj_set_height(ui_operator_5_ratio, 100);
    lv_obj_set_align(ui_operator_5_ratio, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_5_ratio,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_operator_5_ratio, 1, 64);
    lv_arc_set_value(ui_operator_5_ratio, 2);


    ui_operator_6_ratio = lv_arc_create(ui_operators_ratios_arcs_container);
    lv_obj_set_width(ui_operator_6_ratio, 100);
    lv_obj_set_height(ui_operator_6_ratio, 100);
    lv_obj_set_align(ui_operator_6_ratio, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_6_ratio,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_operator_6_ratio, 1, 64);
    lv_arc_set_value(ui_operator_6_ratio, 2);


    ui_operators_levels_label = lv_label_create(ui_operators_page);
    lv_obj_set_width(ui_operators_levels_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operators_levels_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operators_levels_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_operators_levels_label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_operators_levels_label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_operators_levels_label, "____________________ LEVELS ____________________");
    lv_obj_clear_flag(ui_operators_levels_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_operators_levels_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operators_levels_arcs_container = lv_obj_create(ui_operators_page);
    lv_obj_remove_style_all(ui_operators_levels_arcs_container);
    lv_obj_set_width(ui_operators_levels_arcs_container, 800);
    lv_obj_set_height(ui_operators_levels_arcs_container, 110);
    lv_obj_set_align(ui_operators_levels_arcs_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_operators_levels_arcs_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_operators_levels_arcs_container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operators_levels_arcs_container,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_operator_1_level = lv_arc_create(ui_operators_levels_arcs_container);
    lv_obj_set_width(ui_operator_1_level, 100);
    lv_obj_set_height(ui_operator_1_level, 100);
    lv_obj_set_align(ui_operator_1_level, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_1_level,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_operator_1_level, 100);


    ui_operator_2_level = lv_arc_create(ui_operators_levels_arcs_container);
    lv_obj_set_width(ui_operator_2_level, 100);
    lv_obj_set_height(ui_operator_2_level, 100);
    lv_obj_set_align(ui_operator_2_level, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_2_level,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_operator_2_level, 100);


    ui_operator_3_level = lv_arc_create(ui_operators_levels_arcs_container);
    lv_obj_set_width(ui_operator_3_level, 100);
    lv_obj_set_height(ui_operator_3_level, 100);
    lv_obj_set_align(ui_operator_3_level, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_3_level,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_operator_3_level, 100);


    ui_operator_4_level = lv_arc_create(ui_operators_levels_arcs_container);
    lv_obj_set_width(ui_operator_4_level, 100);
    lv_obj_set_height(ui_operator_4_level, 100);
    lv_obj_set_align(ui_operator_4_level, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_4_level,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_operator_4_level, 100);


    ui_operator_5_level = lv_arc_create(ui_operators_levels_arcs_container);
    lv_obj_set_width(ui_operator_5_level, 100);
    lv_obj_set_height(ui_operator_5_level, 100);
    lv_obj_set_align(ui_operator_5_level, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_5_level,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_operator_5_level, 100);


    ui_operator_6_level = lv_arc_create(ui_operators_levels_arcs_container);
    lv_obj_set_width(ui_operator_6_level, 100);
    lv_obj_set_height(ui_operator_6_level, 100);
    lv_obj_set_align(ui_operator_6_level, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operator_6_level,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_operator_6_level, 100);


    ui_operators_labels_container = lv_obj_create(ui_operators_page);
    lv_obj_remove_style_all(ui_operators_labels_container);
    lv_obj_set_width(ui_operators_labels_container, 800);
    lv_obj_set_height(ui_operators_labels_container, 30);
    lv_obj_set_align(ui_operators_labels_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_operators_labels_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_operators_labels_container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operators_labels_container,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_operator_1_label = lv_label_create(ui_operators_labels_container);
    lv_obj_set_width(ui_operator_1_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_1_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_1_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_1_label, "OP 1");
    lv_obj_clear_flag(ui_operator_1_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_operator_1_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_2_label = lv_label_create(ui_operators_labels_container);
    lv_obj_set_width(ui_operator_2_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_2_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_2_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_2_label, "OP 2");
    lv_obj_clear_flag(ui_operator_2_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_operator_2_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_3_label = lv_label_create(ui_operators_labels_container);
    lv_obj_set_width(ui_operator_3_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_3_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_3_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_3_label, "OP 3");
    lv_obj_clear_flag(ui_operator_3_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_operator_3_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_4_label = lv_label_create(ui_operators_labels_container);
    lv_obj_set_width(ui_operator_4_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_4_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_4_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_4_label, "OP 4");
    lv_obj_clear_flag(ui_operator_4_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_operator_4_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_5_label = lv_label_create(ui_operators_labels_container);
    lv_obj_set_width(ui_operator_5_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_5_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_5_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_5_label, "OP 5");
    lv_obj_clear_flag(ui_operator_5_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_operator_5_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operator_6_label = lv_label_create(ui_operators_labels_container);
    lv_obj_set_width(ui_operator_6_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_operator_6_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_operator_6_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_operator_6_label, "OP 6");
    lv_obj_clear_flag(ui_operator_6_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_operator_6_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_io_page = lv_tabview_add_tab(ui_fm_screen_tab, "IO");
    lv_obj_set_flex_flow(ui_io_page, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_io_page, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_io_page, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_io_labels_container = lv_obj_create(ui_io_page);
    lv_obj_remove_style_all(ui_io_labels_container);
    lv_obj_set_width(ui_io_labels_container, 800);
    lv_obj_set_height(ui_io_labels_container, 30);
    lv_obj_set_align(ui_io_labels_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_io_labels_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_io_labels_container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_io_labels_container,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_midi_label = lv_label_create(ui_io_labels_container);
    lv_obj_set_width(ui_midi_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_midi_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_midi_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_midi_label, "MIDI");
    lv_obj_clear_flag(ui_midi_label, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_midi_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_io_controls_container = lv_obj_create(ui_io_page);
    lv_obj_remove_style_all(ui_io_controls_container);
    lv_obj_set_width(ui_io_controls_container, 800);
    lv_obj_set_height(ui_io_controls_container, 160);
    lv_obj_set_align(ui_io_controls_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_io_controls_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_io_controls_container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_io_controls_container,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_midi_roller = lv_roller_create(ui_io_controls_container);
    lv_roller_set_options(ui_midi_roller, "OMNI\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_midi_roller, 100);
    lv_obj_set_height(ui_midi_roller, 120);
    lv_obj_set_x(ui_midi_roller, 195);
    lv_obj_set_y(ui_midi_roller, -56);
    lv_obj_set_align(ui_midi_roller, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_midi_roller, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_add_event_cb(ui_fm_screen_sampler_engine_button, ui_event_fm_screen_sampler_engine_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fm_screen_additive_engine_button, ui_event_fm_screen_additive_engine_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fm_screen_subtractive_engine_button, ui_event_fm_screen_subtractive_engine_button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_algorithm_roller, ui_event_algorithm_roller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sine_wave_button, ui_event_sine_wave_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_square_wave_button, ui_event_square_wave_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_triangle_wave_button, ui_event_triangle_wave_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sawtooth_wave_button, ui_event_sawtooth_wave_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_attack_arc, ui_event_attack_arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_decay_arc, ui_event_decay_arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sustain_arc, ui_event_sustain_arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_release_arc, ui_event_release_arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_1_ratio, ui_event_operator_1_ratio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_2_ratio, ui_event_operator_2_ratio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_3_ratio, ui_event_operator_3_ratio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_4_ratio, ui_event_operator_4_ratio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_5_ratio, ui_event_operator_5_ratio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_6_ratio, ui_event_operator_6_ratio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_1_level, ui_event_operator_1_level, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_2_level, ui_event_operator_2_level, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_3_level, ui_event_operator_3_level, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_4_level, ui_event_operator_4_level, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_5_level, ui_event_operator_5_level, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_operator_6_level, ui_event_operator_6_level, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_midi_roller, ui_event_midi_roller, LV_EVENT_ALL, NULL);

}
