// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: giga_synth_controls

#include "../ui.h"

void ui_sampler_screen_screen_init(void)
{
    ui_sampler_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sampler_screen,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_flex_flow(ui_sampler_screen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_sampler_screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_sampler_screen_tab = lv_tabview_create(ui_sampler_screen, LV_DIR_BOTTOM, 100);
    lv_obj_set_width(ui_sampler_screen_tab, 800);
    lv_obj_set_height(ui_sampler_screen_tab, 480);
    lv_obj_set_align(ui_sampler_screen_tab, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sampler_screen_tab,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags


    ui_sampler_screen_engine_page = lv_tabview_add_tab(ui_sampler_screen_tab, "ENGINE");
    lv_obj_set_flex_flow(ui_sampler_screen_engine_page, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_sampler_screen_engine_page, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sampler_screen_engine_page,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_sampler_screen_fm_engine_button = lv_btn_create(ui_sampler_screen_engine_page);
    lv_obj_set_width(ui_sampler_screen_fm_engine_button, 350);
    lv_obj_set_height(ui_sampler_screen_fm_engine_button, 150);
    lv_obj_set_align(ui_sampler_screen_fm_engine_button, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sampler_screen_fm_engine_button,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_sampler_screen_sampler_engine_button = lv_btn_create(ui_sampler_screen_engine_page);
    lv_obj_set_width(ui_sampler_screen_sampler_engine_button, 350);
    lv_obj_set_height(ui_sampler_screen_sampler_engine_button, 150);
    lv_obj_set_align(ui_sampler_screen_sampler_engine_button, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sampler_screen_sampler_engine_button,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_sampler_screen_additive_engine_button = lv_btn_create(ui_sampler_screen_engine_page);
    lv_obj_set_width(ui_sampler_screen_additive_engine_button, 350);
    lv_obj_set_height(ui_sampler_screen_additive_engine_button, 150);
    lv_obj_set_align(ui_sampler_screen_additive_engine_button, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sampler_screen_additive_engine_button,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_sampler_screen_subtractive_engine_button = lv_btn_create(ui_sampler_screen_engine_page);
    lv_obj_set_width(ui_sampler_screen_subtractive_engine_button, 350);
    lv_obj_set_height(ui_sampler_screen_subtractive_engine_button, 150);
    lv_obj_set_align(ui_sampler_screen_subtractive_engine_button, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sampler_screen_subtractive_engine_button,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_add_event_cb(ui_sampler_screen_fm_engine_button, ui_event_sampler_screen_fm_engine_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sampler_screen_additive_engine_button, ui_event_sampler_screen_additive_engine_button,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sampler_screen_subtractive_engine_button, ui_event_sampler_screen_subtractive_engine_button,
                        LV_EVENT_ALL, NULL);

}
