// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: giga_synth_controls

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_fm_screen
void ui_fm_screen_screen_init(void);
lv_obj_t * ui_fm_screen;
lv_obj_t * ui_fm_screen_tab;
lv_obj_t * ui_fm_screen_engine_page;
lv_obj_t * ui_fm_screen_fm_engine_button;
lv_obj_t * ui_fm_screen_fm_engine_button_label;
void ui_event_fm_screen_sampler_engine_button(lv_event_t * e);
lv_obj_t * ui_fm_screen_sampler_engine_button;
lv_obj_t * ui_fm_screen_sampler_engine_button_label;
void ui_event_fm_screen_additive_engine_button(lv_event_t * e);
lv_obj_t * ui_fm_screen_additive_engine_button;
lv_obj_t * ui_fm_screen_additive_engine_button_label;
void ui_event_fm_screen_subtractive_engine_button(lv_event_t * e);
lv_obj_t * ui_fm_screen_subtractive_engine_button;
lv_obj_t * ui_fm_screen_subtractive_engine_button_label;
lv_obj_t * ui_algorithm_page;
void ui_event_algorithm_roller(lv_event_t * e);
lv_obj_t * ui_algorithm_roller;
lv_obj_t * ui_algorithm_container;
lv_obj_t * ui_algorithm_bar_11;
lv_obj_t * ui_algorithm_bar_10;
lv_obj_t * ui_algorithm_bar_9;
lv_obj_t * ui_algorithm_bar_8;
lv_obj_t * ui_algorithm_bar_7;
lv_obj_t * ui_algorithm_bar_6;
lv_obj_t * ui_algorithm_bar_5;
lv_obj_t * ui_algorithm_bar_4;
lv_obj_t * ui_algorithm_bar_3;
lv_obj_t * ui_algorithm_bar_2;
lv_obj_t * ui_algorithm_bar_1;
lv_obj_t * ui_operator_1_button;
lv_obj_t * ui_operator_1_button_label;
lv_obj_t * ui_operator_2_button;
lv_obj_t * ui_operator_2_button_label;
lv_obj_t * ui_operator_3_button;
lv_obj_t * ui_operator_3_button_label;
lv_obj_t * ui_operator_4_button;
lv_obj_t * ui_operator_4_button_label;
lv_obj_t * ui_operator_5_button;
lv_obj_t * ui_operator_5_button_label;
lv_obj_t * ui_operator_6_button;
lv_obj_t * ui_operator_6_button_label;
lv_obj_t * ui_waveform_page;
void ui_event_sine_wave_button(lv_event_t * e);
lv_obj_t * ui_sine_wave_button;
lv_obj_t * ui_sine_wave_button_label;
void ui_event_square_wave_button(lv_event_t * e);
lv_obj_t * ui_square_wave_button;
lv_obj_t * ui_square_wave_button_label;
void ui_event_triangle_wave_button(lv_event_t * e);
lv_obj_t * ui_triangle_wave_button;
lv_obj_t * ui_triangle_wave_button_label;
void ui_event_sawtooth_wave_button(lv_event_t * e);
lv_obj_t * ui_sawtooth_wave_button;
lv_obj_t * ui_sawtooth_wave_button_label;
lv_obj_t * ui_adsr_page;
lv_obj_t * ui_adsr_labels_container;
lv_obj_t * ui_attack_label;
lv_obj_t * ui_decay_label;
lv_obj_t * ui_sustain_label;
lv_obj_t * ui_release_label;
lv_obj_t * ui_adsr_arcs_container;
void ui_event_attack_arc(lv_event_t * e);
lv_obj_t * ui_attack_arc;
void ui_event_decay_arc(lv_event_t * e);
lv_obj_t * ui_decay_arc;
void ui_event_sustain_arc(lv_event_t * e);
lv_obj_t * ui_sustain_arc;
void ui_event_release_arc(lv_event_t * e);
lv_obj_t * ui_release_arc;
lv_obj_t * ui_operators_page;
lv_obj_t * ui_operators_ratios_label;
lv_obj_t * ui_operators_ratios_arcs_container;
void ui_event_operator_1_ratio(lv_event_t * e);
lv_obj_t * ui_operator_1_ratio;
void ui_event_operator_2_ratio(lv_event_t * e);
lv_obj_t * ui_operator_2_ratio;
void ui_event_operator_3_ratio(lv_event_t * e);
lv_obj_t * ui_operator_3_ratio;
void ui_event_operator_4_ratio(lv_event_t * e);
lv_obj_t * ui_operator_4_ratio;
void ui_event_operator_5_ratio(lv_event_t * e);
lv_obj_t * ui_operator_5_ratio;
void ui_event_operator_6_ratio(lv_event_t * e);
lv_obj_t * ui_operator_6_ratio;
lv_obj_t * ui_operators_levels_label;
lv_obj_t * ui_operators_levels_arcs_container;
void ui_event_operator_1_level(lv_event_t * e);
lv_obj_t * ui_operator_1_level;
void ui_event_operator_2_level(lv_event_t * e);
lv_obj_t * ui_operator_2_level;
void ui_event_operator_3_level(lv_event_t * e);
lv_obj_t * ui_operator_3_level;
void ui_event_operator_4_level(lv_event_t * e);
lv_obj_t * ui_operator_4_level;
void ui_event_operator_5_level(lv_event_t * e);
lv_obj_t * ui_operator_5_level;
void ui_event_operator_6_level(lv_event_t * e);
lv_obj_t * ui_operator_6_level;
lv_obj_t * ui_operators_labels_container;
lv_obj_t * ui_operator_1_label;
lv_obj_t * ui_operator_2_label;
lv_obj_t * ui_operator_3_label;
lv_obj_t * ui_operator_4_label;
lv_obj_t * ui_operator_5_label;
lv_obj_t * ui_operator_6_label;
lv_obj_t * ui_io_page;
lv_obj_t * ui_io_labels_container;
lv_obj_t * ui_midi_label;
lv_obj_t * ui_io_controls_container;
void ui_event_midi_roller(lv_event_t * e);
lv_obj_t * ui_midi_roller;


// SCREEN: ui_sampler_screen
void ui_sampler_screen_screen_init(void);
lv_obj_t * ui_sampler_screen;
lv_obj_t * ui_sampler_screen_tab;
lv_obj_t * ui_sampler_screen_engine_page;
void ui_event_sampler_screen_fm_engine_button(lv_event_t * e);
lv_obj_t * ui_sampler_screen_fm_engine_button;
lv_obj_t * ui_sampler_screen_sampler_engine_button;
void ui_event_sampler_screen_additive_engine_button(lv_event_t * e);
lv_obj_t * ui_sampler_screen_additive_engine_button;
void ui_event_sampler_screen_subtractive_engine_button(lv_event_t * e);
lv_obj_t * ui_sampler_screen_subtractive_engine_button;


// SCREEN: ui_additive_screen
void ui_additive_screen_screen_init(void);
lv_obj_t * ui_additive_screen;
lv_obj_t * ui_addictive_screen_tab;
lv_obj_t * ui_addictive_screen_engine_page;
void ui_event_additive_screen_fm_engine_button(lv_event_t * e);
lv_obj_t * ui_additive_screen_fm_engine_button;
void ui_event_additive_screen_sampler_engine_button(lv_event_t * e);
lv_obj_t * ui_additive_screen_sampler_engine_button;
lv_obj_t * ui_additive_screen_addictive_engine_button;
void ui_event_additive_screen_subtractive_engine_button(lv_event_t * e);
lv_obj_t * ui_additive_screen_subtractive_engine_button;


// SCREEN: ui_subtractive_screen
void ui_subtractive_screen_screen_init(void);
lv_obj_t * ui_subtractive_screen;
lv_obj_t * ui_subtractive_screen_tab;
lv_obj_t * ui_subtractive_screen_engine_page;
void ui_event_subtractive_screen_fm_engine_button(lv_event_t * e);
lv_obj_t * ui_subtractive_screen_fm_engine_button;
void ui_event_subtractive_screen_sampler_engine_button(lv_event_t * e);
lv_obj_t * ui_subtractive_screen_sampler_engine_button;
void ui_event_subtractive_screen_additive_engine_button(lv_event_t * e);
lv_obj_t * ui_subtractive_screen_additive_engine_button;
lv_obj_t * ui_subtractive_screen_subtractive_engine_button;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_fm_screen_sampler_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_sampler_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_sampler_screen_screen_init);
        OnSamplerEngineButtonClicked(e);
    }
}
void ui_event_fm_screen_additive_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnAdditiveEngineButtonClicked(e);
        _ui_screen_change(&ui_additive_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_additive_screen_screen_init);
    }
}
void ui_event_fm_screen_subtractive_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_subtractive_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_subtractive_screen_screen_init);
        OnSubtractiveEngineButtonClicked(e);
    }
}
void ui_event_algorithm_roller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnAlgorithmRollerValueChanged(e);
    }
}
void ui_event_sine_wave_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnSineWaveButtonClicked(e);
    }
}
void ui_event_square_wave_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnSquareWaveButtonClicked(e);
    }
}
void ui_event_triangle_wave_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnTriangleWaveButtonClicked(e);
    }
}
void ui_event_sawtooth_wave_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnSawtoothWaveButtonClicked(e);
    }
}
void ui_event_attack_arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnAttackArcValueChanged(e);
    }
}
void ui_event_decay_arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnDecayArcValueChanged(e);
    }
}
void ui_event_sustain_arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnSustainArcValueChanged(e);
    }
}
void ui_event_release_arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnReleaseArcValueChanged(e);
    }
}
void ui_event_operator_1_ratio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator1RatioArcValueChanged(e);
    }
}
void ui_event_operator_2_ratio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator2RatioArcValueChanged(e);
    }
}
void ui_event_operator_3_ratio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator3RatioArcValueChanged(e);
    }
}
void ui_event_operator_4_ratio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator4RatioArcValueChanged(e);
    }
}
void ui_event_operator_5_ratio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator5RatioArcValueChanged(e);
    }
}
void ui_event_operator_6_ratio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator6RatioArcValueChanged(e);
    }
}
void ui_event_operator_1_level(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator1LevelArcValueChanged(e);
    }
}
void ui_event_operator_2_level(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator2LevelArcValueChanged(e);
    }
}
void ui_event_operator_3_level(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator3LevelArcValueChanged(e);
    }
}
void ui_event_operator_4_level(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator4LevelArcValueChanged(e);
    }
}
void ui_event_operator_5_level(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator5LevelArcValueChanged(e);
    }
}
void ui_event_operator_6_level(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOperator6LevelArcValueChanged(e);
    }
}
void ui_event_midi_roller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnMidiRollerValueChanged(e);
    }
}
void ui_event_sampler_screen_fm_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_fm_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_fm_screen_screen_init);
        OnFmEngineButtonClicked(e);
    }
}
void ui_event_sampler_screen_additive_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnAdditiveEngineButtonClicked(e);
        _ui_screen_change(&ui_additive_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_additive_screen_screen_init);
    }
}
void ui_event_sampler_screen_subtractive_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_subtractive_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_subtractive_screen_screen_init);
        OnSubtractiveEngineButtonClicked(e);
    }
}
void ui_event_additive_screen_fm_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_fm_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_fm_screen_screen_init);
        OnFmEngineButtonClicked(e);
    }
}
void ui_event_additive_screen_sampler_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_sampler_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_sampler_screen_screen_init);
        OnSamplerEngineButtonClicked(e);
    }
}
void ui_event_additive_screen_subtractive_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_subtractive_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_subtractive_screen_screen_init);
        OnSubtractiveEngineButtonClicked(e);
    }
}
void ui_event_subtractive_screen_fm_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_fm_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_fm_screen_screen_init);
        OnFmEngineButtonClicked(e);
    }
}
void ui_event_subtractive_screen_sampler_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_sampler_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_sampler_screen_screen_init);
        OnSamplerEngineButtonClicked(e);
    }
}
void ui_event_subtractive_screen_additive_engine_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnAdditiveEngineButtonClicked(e);
        _ui_screen_change(&ui_additive_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_additive_screen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_fm_screen_screen_init();
    ui_sampler_screen_screen_init();
    ui_additive_screen_screen_init();
    ui_subtractive_screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_fm_screen);
}
