// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: giga_synth_controls

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void OnFmEngineButtonClicked(lv_event_t * e);
void OnSamplerEngineButtonClicked(lv_event_t * e);
void OnAdditiveEngineButtonClicked(lv_event_t * e);
void OnSubtractiveEngineButtonClicked(lv_event_t * e);

void OnAlgorithmRollerValueChanged(lv_event_t * e);

void OnSineWaveButtonClicked(lv_event_t * e);
void OnSquareWaveButtonClicked(lv_event_t * e);
void OnTriangleWaveButtonClicked(lv_event_t * e);
void OnSawtoothWaveButtonClicked(lv_event_t * e);

void OnAttackArcValueChanged(lv_event_t * e);
void OnDecayArcValueChanged(lv_event_t * e);
void OnSustainArcValueChanged(lv_event_t * e);
void OnReleaseArcValueChanged(lv_event_t * e);

void OnOperator1RatioArcValueChanged(lv_event_t * e);
void OnOperator2RatioArcValueChanged(lv_event_t * e);
void OnOperator3RatioArcValueChanged(lv_event_t * e);
void OnOperator4RatioArcValueChanged(lv_event_t * e);
void OnOperator5RatioArcValueChanged(lv_event_t * e);
void OnOperator6RatioArcValueChanged(lv_event_t * e);

void OnOperator1LevelArcValueChanged(lv_event_t * e);
void OnOperator2LevelArcValueChanged(lv_event_t * e);
void OnOperator3LevelArcValueChanged(lv_event_t * e);
void OnOperator4LevelArcValueChanged(lv_event_t * e);
void OnOperator5LevelArcValueChanged(lv_event_t * e);
void OnOperator6LevelArcValueChanged(lv_event_t * e);

void OnMidiRollerValueChanged(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
